sudo: required 
Services:
    - docker 


before_install:
    - docker build -t mouhssineelbazi/docker-react -f Dockerfile.dev .


script:
    - docker run mouhssineelbazi/docker-react npm run test -- --coverage    
    